name: Laravel

on:
  push:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Remove composer.lock
        run: rm composer.lock
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      #       - name: Create Database
      #         run: |
      #           mkdir -p database
      #           touch database/database.sqlite
      - uses: actions/setup-node@master
      - name: Build vue js
        run: |
          npm install
          npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: test_db
          DB_PORT: 33306
          DB_USERNAME: user
          DB_PASSWORD: password
        #         run: vendor/bin/phpunit
        run: |
          php artisan config:clear
          php artisan migrate:fresh
          php artisan db:seed --class=DatabaseTesterSeeder
          php artisan test
      - name: Zip folder build
        run: |
          cd public/
          rm -rf build.zip
          zip -r -q build.zip build
      - uses: EndBug/add-and-commit@v9
        with:
          pull: "--rebase --autostash"
          author_name: "hakim-asrori"
          author_email: "saneglos005@gmail.com"
          message: "build vue js"
      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME_STAGING }}
          host: ${{ secrets.HOST_STAGING }}
          password: ${{ secrets.PASSWORD_STAGING }}
          script: "cd /home/u890410510/domains/berobatplus.shop/hakim-ta/API-Website && sh deploy.sh"
